### PR TITLE
Need add Start Of the Services on Reboot: Start nginx + php-fpm services

### PR DESCRIPTION
**Pull request by stevemcquaid**
Changes per PR#93: Need add Start Of the Services on Reboot
https://github.com/ansible/ansible-examples/issues/93

Thanks to @pete-experimenter for showing that I'm not the only one this happens to.

### CODE REVIEW

**Comment by varnav** [comment]
I think it's better to add 'enabled=yes' to the end of the restarting line in /nginx/handlers/main.yml

**Comment by stevemcquaid** [comment]
@varnav if that is done, this fails: LN 30: wordpress-nginx/roles/wordpress/tasks/main.yml

**Comment by varnav** [comment]
I used line:

`service: name=nginx state=restarted enabled=yes`

and it worked well. But restart fails for another reason, there is a duplicate line 

`Listen 80 default_server`

in nginx.conf and /conf.d/default.conf

**Comment by gregdek** [comment]
Do we have some confirmation that the latest sample code here works? @stevemcquaid?

**Comment by stevemcquaid** [comment]
@gregdek  I will test against a clean vm in a few minutes. pulling in the changes to upstream made by @varnav

@varnav  - the reason I proposed these changes versus your PR #122 is because you need to restart nginx AFTER you setup wordpress, not before.

Update to PR coming :D

**Comment by stevemcquaid** [comment]
This PR is updated - I edited the commit above so that it only does the single change necessary to make it work. Tested on CentOS6.6. I did need to enable sudo in site.yml though. LMK if that should be reflected in the commit.

Also - should this change be in tasks or handlers?

**Comment by gregdek** [comment]
@varmav thoughts here?

**Comment by varnav** [comment]
Hmm, I don't see anything but single end of line in this commit.

**Comment by varnav** [comment]
No, no thoughts from me. :)

**Comment by gregdek** [comment]
OK, merging. Thanks!

**Pull request merged**
